linters-settings:
  revive:
    min-confidence: 0
    rules:
      - name: unused-parameter
        disabled: true
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - revive
    - typecheck
    - misspell
    - unconvert
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - unused
        - unparam
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0

